# Generated by Django 4.2 on 2026-02-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_superadminbiometric_emergencypaperkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('imported', models.BooleanField(default=False)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
