# Generated by Django 4.2 on 2026-02-17 20:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_faculty_phone_student_phone_user_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupselection',
            options={'ordering': ['submitted_at']},
        ),
        migrations.AddField(
            model_name='groupselection',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=datetime.datetime(2026, 2, 17, 20, 45, 37, 922344, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SelectionQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed', models.BooleanField(default=False)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.domain')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.faculty')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.topic')),
            ],
            options={
                'ordering': ['requested_at'],
            },
        ),
    ]
