import React, { useState, useEffect } from 'react';
import { Container, Card, Row, Col, Button, Table, Alert, Modal, Form, Badge } from 'react-bootstrap';
import axios from 'axios';
import { toast } from 'react-toastify';
import { 
  Key, Printer, Download, ShieldLock, 
  Eye, EyeSlash, Plus, Trash, Clock 
} from 'react-bootstrap-icons';

function SuperAdminPaperKeys({ user }) {
  const [paperKeys, setPaperKeys] = useState([]);
  const [loading, setLoading] = useState(true);
  const [showGenerateModal, setShowGenerateModal] = useState(false);
  const [showViewModal, setShowViewModal] = useState(false);
  const [showRecoveryModal, setShowRecoveryModal] = useState(false);
  const [selectedKey, setSelectedKey] = useState(null);
  const [newKeys, setNewKeys] = useState([]);
  const [recoveryData, setRecoveryData] = useState({
    username: '',
    paperKey: '',
    showKey: false
  });
  const [generating, setGenerating] = useState(false);

  useEffect(() => {
    fetchPaperKeys();
  }, []);

  const fetchPaperKeys = async () => {
    try {
      const response = await axios.get('/super-admin/paper-keys/');
      setPaperKeys(response.data.keys || []);
    } catch (error) {
      console.error('Error fetching paper keys:', error);
      toast.error('Failed to load paper keys');
    } finally {
      setLoading(false);
    }
  };

  const generatePaperKeys = async () => {
    setGenerating(true);
    try {
      const response = await axios.post('/super-admin/generate-paper-keys/');
      
      if (response.data.success) {
        setNewKeys(response.data.keys);
        toast.success('✅ New paper keys generated!');
        fetchPaperKeys();
      }
    } catch (error) {
      toast.error('Failed to generate paper keys');
    } finally {
      setGenerating(false);
    }
  };

  const downloadKeysAsPDF = () => {
    // Create printable content
    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
      <html>
        <head>
          <title>GroupFlow - Emergency Paper Keys</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 40px; }
            h1 { color: #dc3545; }
            .key-container { 
              border: 2px dashed #dc3545; 
              padding: 20px; 
              margin: 20px 0;
              background: #fff3f3;
            }
            .key { 
              font-family: monospace; 
              font-size: 24px; 
              letter-spacing: 2px;
              background: #333;
              color: #ffd700;
              padding: 10px;
              text-align: center;
              margin: 10px 0;
            }
            .warning { 
              color: #dc3545; 
              font-weight: bold;
              border: 2px solid #dc3545;
              padding: 15px;
              margin: 20px 0;
            }
            .footer { margin-top: 40px; font-size: 12px; color: #666; }
          </style>
        </head>
        <body>
          <h1>🔐 GROUPFLOW EMERGENCY PAPER KEYS</h1>
          <div class="warning">
            ⚠️ KEEP THIS DOCUMENT IN A PHYSICAL SAFE ⚠️<br>
            Each key can be used ONLY ONCE for emergency recovery.
          </div>
          
          <div class="key-container">
            <h3>Your Emergency Recovery Keys:</h3>
            ${newKeys.map(k => `
              <div class="key">${k.key}</div>
              <p style="text-align: center;">${k.hint} - Generated: ${new Date().toLocaleString()}</p>
              <hr>
            `).join('')}
          </div>

          <div class="warning">
            📌 INSTRUCTIONS:<br>
            1. Cut this page and store each key separately<br>
            2. Never store digitally<br>
            3. Each key works only once<br>
            4. Generate new keys after using one<br>
            5. Keep in fireproof safe
          </div>

          <div class="footer">
            Generated by: ${user?.username}<br>
            Date: ${new Date().toLocaleString()}<br>
            IP: ${window.location.hostname}<br>
            System: GroupFlow Super Admin
          </div>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  const deletePaperKey = async (keyId) => {
    if (!window.confirm('Are you sure? This key will be permanently deleted.')) return;
    
    try {
      await axios.delete(`/super-admin/paper-key/${keyId}/`);
      toast.warning('Key deleted');
      fetchPaperKeys();
    } catch (error) {
      toast.error('Failed to delete key');
    }
  };

  const testPaperKeyRecovery = async () => {
    if (!recoveryData.username || !recoveryData.paperKey) {
      toast.error('Please enter username and paper key');
      return;
    }

    try {
      const response = await axios.post('/super-admin/emergency-paper-recovery/', {
        username: recoveryData.username,
        paper_key: recoveryData.paperKey
      });

      if (response.data.success) {
        toast.warning(
          <div>
            <h6>✅ Recovery Successful!</h6>
            <p>Temporary Password: <strong>{response.data.temp_password}</strong></p>
            <p className="text-danger">Change password immediately!</p>
          </div>,
          { autoClose: 15000 }
        );
        setShowRecoveryModal(false);
        setRecoveryData({ username: '', paperKey: '', showKey: false });
        fetchPaperKeys();
      }
    } catch (error) {
      toast.error(error.response?.data?.error || 'Recovery failed');
    }
  };

  return (
    <Container className="mt-5">
      <Card>
        <Card.Header className="bg-warning">
          <Row>
            <Col>
              <h3><Key className="me-2" /> Emergency Paper Keys Management</h3>
            </Col>
            <Col className="text-end">
              <Button 
                variant="dark" 
                onClick={() => setShowGenerateModal(true)}
                className="me-2"
              >
                <Plus /> Generate New Keys
              </Button>
              <Button 
                variant="danger" 
                onClick={() => setShowRecoveryModal(true)}
              >
                Test Recovery
              </Button>
            </Col>
          </Row>
        </Card.Header>
        <Card.Body>
          <Alert variant="danger">
            <ShieldLock className="me-2" />
            <strong>⚠️ CRITICAL SECURITY:</strong> Paper keys are your last line of defense. 
            Store them in a PHYSICAL SAFE. Never store digitally.
          </Alert>

          {loading ? (
            <div className="text-center">Loading...</div>
          ) : (
            <>
              <Row className="mb-4">
                <Col md={3}>
                  <Card className="bg-primary text-white">
                    <Card.Body className="text-center">
                      <h3>{paperKeys.length}</h3>
                      <p>Active Keys</p>
                    </Card.Body>
                  </Card>
                </Col>
                <Col md={3}>
                  <Card className="bg-success text-white">
                    <Card.Body className="text-center">
                      <h3>{paperKeys.filter(k => !k.used_at).length}</h3>
                      <p>Unused Keys</p>
                    </Card.Body>
                  </Card>
                </Col>
                <Col md={3}>
                  <Card className="bg-warning text-white">
                    <Card.Body className="text-center">
                      <h3>{paperKeys.filter(k => k.used_at).length}</h3>
                      <p>Used Keys</p>
                    </Card.Body>
                  </Card>
                </Col>
                <Col md={3}>
                  <Card className="bg-info text-white">
                    <Card.Body className="text-center">
                      <h3>{paperKeys.length > 0 ? 
                        Math.min(...paperKeys.map(k => new Date(k.created_at))) : 'N/A'}</h3>
                      <p>Oldest Key</p>
                    </Card.Body>
                  </Card>
                </Col>
              </Row>

              <Table striped bordered hover>
                <thead>
                  <tr>
                    <th>Key Hint</th>
                    <th>Created</th>
                    <th>Status</th>
                    <th>Used At</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {paperKeys.map((key, index) => (
                    <tr key={key.id || index}>
                      <td>
                        <Key className="me-2 text-warning" />
                        {key.key_hint}
                      </td>
                      <td>{new Date(key.created_at).toLocaleString()}</td>
                      <td>
                        {key.used_at ? (
                          <Badge bg="danger">Used</Badge>
                        ) : (
                          <Badge bg="success">Active</Badge>
                        )}
                      </td>
                      <td>
                        {key.used_at ? new Date(key.used_at).toLocaleString() : '—'}
                      </td>
                      <td>
                        <Button 
                          variant="outline-danger" 
                          size="sm"
                          onClick={() => deletePaperKey(key.id)}
                          disabled={key.used_at}
                        >
                          <Trash /> Delete
                        </Button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </Table>

              <Alert variant="info" className="mt-3">
                <h6>📋 Paper Key Best Practices:</h6>
                <ul className="mb-0">
                  <li>Print keys and store in separate physical locations</li>
                  <li>Use a fireproof safe or bank locker</li>
                  <li>Never store keys digitally (no photos, no cloud)</li>
                  <li>Generate new keys immediately after using one</li>
                  <li>Inform trusted person about key location for emergencies</li>
                </ul>
              </Alert>
            </>
          )}
        </Card.Body>
      </Card>

      {/* Generate Keys Modal */}
      <Modal show={showGenerateModal} onHide={() => setShowGenerateModal(false)} size="lg">
        <Modal.Header closeButton className="bg-warning">
          <Modal.Title>Generate New Paper Keys</Modal.Title>
        </Modal.Header>
        <Modal.Body>
          {newKeys.length === 0 ? (
            <>
              <Alert variant="warning">
                <h6>⚠️ Before Generating:</h6>
                <p>You are about to create 5 new emergency paper keys. These keys can be used 
                to recover your super admin account if you lose access.</p>
              </Alert>
              
              <div className="text-center">
                <Button 
                  variant="warning" 
                  size="lg"
                  onClick={generatePaperKeys}
                  disabled={generating}
                >
                  {generating ? 'Generating...' : 'Generate 5 New Paper Keys'}
                </Button>
              </div>
            </>
          ) : (
            <>
              <Alert variant="danger">
                <h5>🔐 YOUR NEW PAPER KEYS</h5>
                <p className="mb-0">Print this page immediately and store in a physical safe!</p>
              </Alert>

              <div className="p-4 bg-dark text-light rounded">
                {newKeys.map((key, index) => (
                  <div key={index} className="mb-4">
                    <h6>{key.hint}</h6>
                    <div className="d-flex justify-content-between align-items-center">
                      <code className="text-warning" style={{ fontSize: '1.2rem' }}>
                        {recoveryData.showKey ? key.key : '••••-••••-••••-••••'}
                      </code>
                      <div>
                        <Button 
                          variant="outline-light" 
                          size="sm"
                          className="me-2"
                          onClick={() => navigator.clipboard.writeText(key.key)}
                        >
                          Copy
                        </Button>
                        <Button 
                          variant="outline-light" 
                          size="sm"
                          onClick={() => setRecoveryData({...recoveryData, showKey: !recoveryData.showKey})}
                        >
                          {recoveryData.showKey ? <EyeSlash /> : <Eye />}
                        </Button>
                      </div>
                    </div>
                    {index < newKeys.length - 1 && <hr className="bg-light" />}
                  </div>
                ))}
              </div>

              <Row className="mt-4">
                <Col>
                  <Button 
                    variant="success" 
                    onClick={downloadKeysAsPDF}
                    className="w-100"
                  >
                    <Printer className="me-2" /> Print / Save as PDF
                  </Button>
                </Col>
                <Col>
                  <Button 
                    variant="primary" 
                    onClick={() => {
                      setNewKeys([]);
                      setShowGenerateModal(false);
                    }}
                    className="w-100"
                  >
                    <Download className="me-2" /> I've Saved Them
                  </Button>
                </Col>
              </Row>
            </>
          )}
        </Modal.Body>
      </Modal>

      {/* Test Recovery Modal */}
      <Modal show={showRecoveryModal} onHide={() => setShowRecoveryModal(false)}>
        <Modal.Header closeButton className="bg-danger text-white">
          <Modal.Title>Test Paper Key Recovery</Modal.Title>
        </Modal.Header>
        <Modal.Body>
          <Alert variant="warning">
            <h6>⚠️ Test Recovery Mode</h6>
            <p>This simulates an emergency recovery using a paper key. 
               A temporary password will be generated.</p>
          </Alert>

          <Form>
            <Form.Group className="mb-3">
              <Form.Label>Username</Form.Label>
              <Form.Control
                type="text"
                value={recoveryData.username}
                onChange={(e) => setRecoveryData({...recoveryData, username: e.target.value})}
                placeholder="Enter username to recover"
              />
            </Form.Group>

            <Form.Group className="mb-3">
              <Form.Label>Paper Key</Form.Label>
              <InputGroup>
                <Form.Control
                  type={recoveryData.showKey ? "text" : "password"}
                  value={recoveryData.paperKey}
                  onChange={(e) => setRecoveryData({...recoveryData, paperKey: e.target.value})}
                  placeholder="XXXX-XXXX-XXXX-XXXX"
                />
                <Button 
                  variant="outline-secondary"
                  onClick={() => setRecoveryData({...recoveryData, showKey: !recoveryData.showKey})}
                >
                  {recoveryData.showKey ? <EyeSlash /> : <Eye />}
                </Button>
              </InputGroup>
              <Form.Text className="text-muted">
                Enter the full paper key including hyphens
              </Form.Text>
            </Form.Group>
          </Form>
        </Modal.Body>
        <Modal.Footer>
          <Button variant="secondary" onClick={() => setShowRecoveryModal(false)}>
            Cancel
          </Button>
          <Button variant="danger" onClick={testPaperKeyRecovery}>
            Test Recovery
          </Button>
        </Modal.Footer>
      </Modal>
    </Container>
  );
}

export default SuperAdminPaperKeys;